# MCP Notebook AI Agent Configuration File
# This file contains all configuration settings for the MCP Notebook AI Agent

# Application Settings
app:
  name: "MCP Notebook AI Agent"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8001
  debug: false
  log_level: "INFO"

# LLM Configuration
llm:
  model: "gemini-2.5-flash"
  temperature: 0.7
  max_tokens: 2048
  timeout: 30
  # Authentication via Google Cloud Service Account
  auth_method: "service_account"

# MCP Server Configuration
mcp:
  timeout: 30
  retry_attempts: 3
  connection_retry_delay: 2  # seconds between retries

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    enabled: true
    path: "logs/mcp_agent.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true

# Security Configuration
security:
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

# Development/Production Overrides
development:
  debug: true
  log_level: "DEBUG"
  
production:
  debug: false
  log_level: "WARNING"
  security:
    cors:
      allow_origins: ["http://localhost:9003"]  # Only allow web interface
